title: Cody Coponiti # your name (or website title) here
logo: "/images/Profile%20pic.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of Oklhoma GIS Masters student
  <br><br>
 
   M.A. National Security Studies form the Institute for World Politics 
   <br><br>

remote_theme: pages-themes/minimal@v0.2.0

